control_brace_style = "AlwaysSameLine"
imports_indent = "Visual"
match_block_trailing_comma = true
max_width = 80
reorder_imports = true
struct_field_align_threshold = 20
struct_lit_single_line = false
trailing_comma = "Never"